# Position of the item name after a wish

WISH_ITEM_POS = {
            "top": 1055,
            "left": 615,
            "width": 1036,
            "height": 121
            }

# Position of an item unique to the summon screen

SUMMON_SCREEN = {
            "top": 1834,
            "left": 160,
            "width": 102,
            "height": 138
            }


VALID_BANNERS = {'Character Event Warp', 'Light Cone Event Warp', 'Regular Warp'}

SUMMON_SCREEN_PATH = 'assets/exchange.png'

# Position of the x1 warp button
X1_WARP = (1919, 2335, 567, 91)
# Position of the x10 warp button
X10_WARP = (1923, 2998, 561, 84)

VALID_ITEMS = {
    "arrows",
    "cornucopia",
    "collapsing sky",
    "amber",
    "void",
    "chorus",
    "data bank",
    "darting arrow",
    "fine fruit",
    "shattered home",
    "defense",
    "loop",
    "meshing cogs",
    "passkey",
    "adversarial",
    "multiplication",
    "mutual demise",
    "pioneering",
    "hidden shadow",
    "mediation",
    "sagacity",
    "shadowburn",
    "reminiscence",
    "post-op conversation",
    "good night and sleep well",
    "day one of my new life",
    "only silence remains",
    "memories of the past",
    "the moles welcome you",
    "the birth of the self",
    "shared feeling",
    "eyes of the prey",
    "landau's choice",
    "swordplay",
    "planetary rendezvous",
    "a secret vow",
    "make the world clamor",
    "perfect timing",
    "resolution shines as pearls of sweat",
    "trend of the universal market",
    "subscribe for more!",
    "dance! dance! dance!",
    "under the blue sky",
    "geniuses' repose",
    "quid prop quo",
    "fermata",
    "we are wildfire",
    "river flows in spring",
    "past and future",
    "woof! walk time!",
    "the seriousness of breakfast",
    "warmth shortens cold nights",
    "we will meet again",
    "this is me!",
    "return to darkness",
    "carve the moon, weave the clouds",
    "nowhere to run",
    "today is another peaceful day",
    "what is real?",
    "dreamvile adventure",
    "final victor",
    "flames afar",
    "destiny's threads forewoven",
    "the day the cosmos fell",
    "it's showtime",
    "indelible promise",
    "concert for two",
    "boundless choreo",
    "after the charmony fall",
    "poised to bloom",
    "shadowed by night",
    "dream's montage",
    "victory in a blink",
    "geniuses' greetings",
    "sweat now, cry later",
    "journey, forever peaceful"
    "the story's next page",
    "unto tomorrow's morrow",
    "in pursuit of the wind",
    "the flower remembers",
    "a trail of bygone blood",
    "a dream scented in wheat",
    "holiday thermae escapade",
    "see you at the end",
    "before the tutorial mission starts",
    "hey, over here",
    "for tomorrow's journey",
    "ninja record: sound hunt",
    "the great cosmic enterprise",
    "the forever victual",
    "on the fall of an aeon",
    "cruising in the stellar sea",
    "texture of memories",
    "solitary healing",
    "eternal calculus",
    "memory's curtain never falls",
    "night on the milky way",
    "in the night",
    "something irreplaceable",
    "but the battle isn't over",
    "in the name of the world",
    "moments of victory",
    "patience is all you need",
    "incessant rain",
    "echoes of the coffin",
    "time waits for no one",
    "i shall be my own sword",
    "brighter than the sun",
    "worrisome, blissful",
    "night of fright",
    "an instant before a gaze",
    "past self in mirror",
    "baptism of pure thought",
    "earthly escapade",
    "reforged remembrance",
    "inherently unjust destiny",
    "along the passing shore",
    "whereabouts should dreams rest",
    "flowing nightglow",
    "sailing towards a second life",
    "yet hope is priceless",
    "those many springs",
    "dance at sunset",
    "i venture forth to hunt",
    "scent alone stays true",
    "ninjutsu inscription: dazzling evilbreaker",
    "a grounded ascent",
    "long road leads home",
    "time woven into gold",
    "into the unreachable veil",
    "if time were a flower",
    "flame of blood, blaze my path",
    "make farewells more beautiful",
    "life should be cast to flames",
    "long may rainbows adorn the sky",
    "lies dance on the breeze",
    "thus burns the dawn",
    "a thankless coronation",
    "the hell where ideals burn",
    "why does the ocean sing",
    "epoch etched in golden blood",
    "cerydera",
    "hysilens",
    "hyacine",
    "phainon",
    "castorice",
    "cipher",
    "anaxa",
    "mydei",
    "tribbie",
    "aglaea",
    "the herta",
    "rappa",
    "boothill",
    "jade",
    "sunday",
    "firefly",
    "robin",
    "acheron",
    "black swan",
    "sparkle",
    "dr. ratio",
    "aventurine",
    "ruan mei",
    "argenti",
    "fugue",
    "linghsa",
    "yunli",
    "feixiao",
    "jiaoqui",
    "huohuo",
    "dan heng • imbibitor lunae",
    "jingliu",
    "bailu",
    "yanqing",
    "fu xuan",
    "blade",
    "jing yuan",
    "luocha",
    "topaz & numpy",
    "clara",
    "gepard",
    "seele",
    "bronya",
    "archer",
    "saber",
    "silver wolf",
    "kafka",
    "welt",
    "himeko",
    "misha",
    "gallagher",
    "moze",
    "hanya",
    "xuyei",
    "guinaifen",
    "yukong",
    "sushang",
    "tingyun",
    "qingque",
    "luka",
    "lynx",
    "hook",
    "sampo",
    "pela",
    "natasha",
    "serval",
    "herta",
    "astra",
    "arlan",
    "dang heng",
    "march 7th"
}

VALID_DICT = {}

for item in VALID_ITEMS:
    modified = item.replace("!", "l")
    VALID_DICT[modified] = item